Cover additional PHP keyword edge cases
spawnia/sailor pull request #68
Opened 2022-07-06 15:15 UTC by spawnia

Resolves https://github.com/spawnia/sailor/issues/63

2022-07-06 17:09 UTC, simPod approved these changes

2022-07-06 18:30 UTC, simPod requested changes
I tried it in my project and we generate wrong 

```php
/**
 * @property array<int, A|B> $devices
 * @property string $__typename
 */
class QueryName extends \Spawnia\Sailor\ObjectLike
{
    /**
     * @param array<int, A|B> $xxx
     */
    public static function make($xxx): self
``` where `B` should be `_B`

2022-07-06 18:32 UTC, simPod commented
But it is broken in the master as well. So we can merge this and I'll look into the issue.

2022-07-06 20:24 UTC, simPod commented on examples/php-keywords/src/test.php
> +$result = \Spawnia\Sailor\Simple\Operations\MyObjectQuery::execute();
is this correct here?

2022-07-06 20:31 UTC, simPod commented on examples/php-keywords/test.sh
> +#!/usr/bin/env bash
I tried and it's missing `+x` permissions.

2022-07-07 08:09 UTC, spawnia commented on examples/php-keywords/src/test.php
> +$result = \Spawnia\Sailor\Simple\Operations\MyObjectQuery::execute();
no, fixed.

2022-07-07 08:09 UTC, spawnia commented on examples/php-keywords/test.sh
> +#!/usr/bin/env bash
fixed.

2022-07-07 08:31 UTC, simPod commented on Makefile
> +examples: ## Test examples
```suggestion
test-examples:
```

2022-07-07 09:03 UTC, simPod approved these changes
Running this in prod rn with no issues.

2022-07-07 09:08 UTC, merged

2022-07-07 09:11 UTC, spawnia commented
> Running this in prod rn with no issues.

That is the best kind of review 😉

How do you feel about cutting a stable release of Sailor? We are using it in a bunch of projects ourselves and have not run into major issues. Anything you would change before?

2022-07-07 09:15 UTC, simPod commented
I'm slowly adopting it for more complex use-cases. Overall, was using it only for basic operations until recently on several projects.

I'd give it a bit more time to see whether I encounter other issues or not.